spring:
  mvc:
    enable-global-res: true
  threads:
    virtual:
      enabled: true
  application:
    name: demo-application
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Aa123456#
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80
mybatis-flex:
  global-config:
    print-banner: false
logging:
  level:
    "[com.example.demo.mapper]": debug
